### PR TITLE
Added Advanced Stats Module

### PR DESCRIPTION
**Pull request by FanaHOVA**
Taking over orphaned #53. 

@dblock I also added dotenv to help with the ENV issue for generating VCRs. I lazily added DeepSource as well to run transformers for me because I forget to locally :)

### CODE REVIEW

**Review by rodolfobandeira — APPROVED** [review]

**Comment by rodolfobandeira** [comment]
LGTM. I'm not sure about the deepsource and .env but I'll let more people comment on that

**Review by dblock — CHANGES_REQUESTED** [review]
DotEnv is cool, thanks.

I've never heard of DeepSource until now. Let's leave it out for this PR, I presume we'd want it with badges & al here if we do? As is it just adds a file that will be dangling here.

**Comment by dblock** [comment]
> LGTM. I'm not sure about the deepsource and .env but I'll let more people comment on that

The .env construct is pretty common, instead of having to rely on `export` you can have a .env file that does not get checked in (we already include it in .gitignore) and load it via `dotenv`. That's what I typically do in development and the addition here makes it "just work".

**Comment by FanaHOVA** [comment]
@dblock Makes sense, just removed the .toml file. Should be good to go.

**Comment by dblock** [comment]
Merged, thanks.

**Pull request merged**
